version: '2'
services:
  generator-frontend:
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 5555
      unhealthy_threshold: 3
      initializing_timeout: 60000
      interval: 2000
      strategy: recreate
      reinitializing_timeout: 6000