package io.adopteunops.etl.domain;

public enum TypeValidation {
    FORMAT_JSON,
    MANDATORY_FIELD,
    BLACK_LIST_FIELD,
    MAX_FIELD,
    MAX_MESSAGE_SIZE,
    ADD_FIELD,
    DELETE_FIELD,
    RENAME_FIELD,
    FORMAT_DATE,
    FORMAT_BOOLEAN,
    FORMAT_GEOPOINT,
    FORMAT_DOUBLE,
    FORMAT_LONG,
    FORMAT_IP,
    FIELD_EXIST,
    LOOKUP_LIST,
    LOOKUP_EXTERNAL
}
